- name: To Install the NGINX and start the NGINX
  hosts: web
  becomes: yes # For given permissions to Sudo user
  tasks:
    - name: To Install the nginx Service
      ansible.builtin.service module:
      - name: nginx
          state: present # Present - installed and absent - Removed
          enabled: yes